// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqzKeC9HLqWkBUh_V0QTSvaszbirE97g',
    appId: '1:175134395680:web:abf965bc01110f87aedb45',
    messagingSenderId: '175134395680',
    projectId: 'projeto3-6cdb3',
    authDomain: 'projeto3-6cdb3.firebaseapp.com',
    databaseURL: 'https://projeto3-6cdb3-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cdb3.firebasestorage.app',
    measurementId: 'G-2SFTBEE36D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUuPNtPPyBH6HdTruCJLkQYmtxF3CwlY',
    appId: '1:175134395680:android:326c30d45e045107aedb45',
    messagingSenderId: '175134395680',
    projectId: 'projeto3-6cdb3',
    databaseURL: 'https://projeto3-6cdb3-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2TE8KR-AjHEfjnQBXXU1YpIJTJtgkCo',
    appId: '1:175134395680:ios:c8dba6afbb059985aedb45',
    messagingSenderId: '175134395680',
    projectId: 'projeto3-6cdb3',
    databaseURL: 'https://projeto3-6cdb3-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cdb3.firebasestorage.app',
    iosBundleId: 'com.example.projeto3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt2TE8KR-AjHEfjnQBXXU1YpIJTJtgkCo',
    appId: '1:175134395680:ios:c8dba6afbb059985aedb45',
    messagingSenderId: '175134395680',
    projectId: 'projeto3-6cdb3',
    databaseURL: 'https://projeto3-6cdb3-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cdb3.firebasestorage.app',
    iosBundleId: 'com.example.projeto3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOqzKeC9HLqWkBUh_V0QTSvaszbirE97g',
    appId: '1:175134395680:web:c024cf3fd6067911aedb45',
    messagingSenderId: '175134395680',
    projectId: 'projeto3-6cdb3',
    authDomain: 'projeto3-6cdb3.firebaseapp.com',
    databaseURL: 'https://projeto3-6cdb3-default-rtdb.firebaseio.com',
    storageBucket: 'projeto3-6cdb3.firebasestorage.app',
    measurementId: 'G-SHQBVBFQF9',
  );
}
